config/routes.rb
Rails.application.routes.draw do
  resources :demos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, :address
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/demo.rb
class Demo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    
    has_one :address

    validates_with CustomValidator

    validates :lastname, presence: true, if: :first_name_present?

    validates :firstname,:lastname, format: { with: /\A[A-Z]+\Z/,
        message: "Capital Letters Only..!!" }, allow_blank: true
    
    validates :email, uniqueness: true, presence: true, format: {with: /\A[a-zA-Z]+[\.?\w]*@([a-zA-Z])+(\.[a-z]{2,3})+\Z/, message: "Invalid Format Of Email ID..!!"}

    validates :age, numericality: {greater_than_or_equal_to: 15, less_than_or_equal_to: 40, only_integer: true}, allow_blank: true

    validates :username, uniqueness: {scope: :email, message: "Should Have Unique Mail"}, exclusion: {in: %w(aashka zeel), message: "Don't use common Name..!!"}

    validates :password, length: {minimum: 8}, confirmation: true

    validates :password_confirmation, presence: true

    validates :website, format: { with: /\Ahttps?\:\/\/\www\.(\w+)(\.(\D\w{2,3})+)(\/\w|\s|\n|\W)*\Z/, message: "Enter Valid Website Name" }

    

    def first_name_present?
        firstname.present?
    end

end

app/controllers/address_controller.rb
class AddressController < ApplicationController
    before_action :set_address, only: [:edit, :update, :show, :destroy]

    def index
        @addresses = Address.all
    end

    def show
    end
    
    private
    def set_address
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  before_action :set_demo, only: [:show, :edit, :update, :destroy]

  # GET /demos
  # GET /demos.json
  def index
    @demos = Demo.all
  end

  # GET /demos/1
  # GET /demos/1.json
  def show
  end

  # GET /demos/new
  def new
    @demo = Demo.new
  end

  # GET /demos/1/edit
  def edit
  end

  # POST /demos
  # POST /demos.json
  def create
    @demo = Demo.new(demo_params)

    respond_to do |format|
      if @demo.save
        format.html { redirect_to @demo, notice: 'Demo was successfully created.' }
        format.json { render :show, status: :created, location: @demo }
      else
        format.html { render :new }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demos/1
  # PATCH/PUT /demos/1.json
  def update
    respond_to do |format|
      if @demo.update(demo_params)
        format.html { redirect_to @demo, notice: 'Demo was successfully updated.' }
        format.json { render :show, status: :ok, location: @demo }
      else
        format.html { render :edit }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demos/1
  # DELETE /demos/1.json
  def destroy
    @demo.destroy
    respond_to do |format|
      format.html { redirect_to demos_url, notice: 'Demo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demo
      @demo = Demo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demo_params
      params.require(:demo).permit(:name, :age)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show, :destroy]

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def update
        respond_to do |format|
            if @user.update(user_params)
                format.html { redirect_to users_path, notice: 'User Updated Successfully' }
            else
                format.html { render :new }
            end
        end
    end

    def destroy
        @user.destroy
        respond_to do |format|
          format.html { redirect_to users_path, notice: 'User was destroyed.' }
        end
      end


    def create
        @user = User.new(user_params)
        respond_to do |format|
            if @user.save
                format.html { redirect_to users_path	, notice: 'User Created Successfully' }
            else
                format.html { render :new }
            end
        end
    end

    private
    def set_user
        @user = User.find(params[:id])
    end
    def user_params
        params.require(:user).permit(:firstname, :lastname, :email, :age, :degree, :year, :com_name, :website, :username, :password,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/views/address/index.html.erb
<h1>USERS ADDRESSES</h1>

app/views/address/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= address.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @demo.age %>
</p>

<%= link_to 'Edit', edit_demo_path(@demo) %> |
<%= link_to 'Back', demos_path %>

app/views/demos/_form.html.erb
<%= form_with(model: demo, local: true) do |form| %>
  <% if demo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(demo.errors.count, "error") %> prohibited this demo from being saved:</h2>

      <ul>
        <% demo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/demos/edit.html.erb
<h1>Editing Demo</h1>

<%= render 'form', demo: @demo %>

<%= link_to 'Show', @demo %> |
<%= link_to 'Back', demos_path %>

app/views/demos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Demos</h1>

<table border = "1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @demos.each do |demo| %>
      <tr>
        <td><%= demo.name %></td>
        <td><%= demo.age %></td>
        <td><%= link_to 'Show', demo %></td>
        <td><%= link_to 'Edit', edit_demo_path(demo) %></td>
        <td><%= link_to 'Destroy', demo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Demo', new_demo_path %>

app/views/demos/new.html.erb
<h1>New Demo</h1>

<%= render 'form', demo: @demo %>

<%= link_to 'Back', demos_path %>

app/views/demos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @demo.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @demo.age %>
</p>

<%= link_to 'Edit', edit_demo_path(@demo) %> |
<%= link_to 'Back', demos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
      <h2><%= pluralize(user.errors.count, "Errors") %>  Thrown:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
    <% end %>
      </ul>
  <% end %>

    <%= form.label :First_Name %>
    <%= form.text_field :firstname %>
    <br><br>
    
    <%= form.label :Last_Name %>
    <%= form.text_field :lastname %>
    <br><br>
    
    <%= form.label :Email %>
    <%= form.text_field :email %>
    <br><br>
    
    <%= form.label :Age %>
    <%= form.number_field :age %>
    <br><br>
    
    <%= form.label :Degree %>
    <%= form.text_field :degree %>
    <br><br>
    
    <%= form.label :Year_Completed %>
    <%= form.number_field :year %>
    <br><br>

    <%= form.label :Company_Name %>
    <%= form.text_field :com_name %>
    <br><br>

    <%= form.label :Website %>
    <%= form.text_field :website %>
    <br><br>

    <%= form.label :Username %>
    <%= form.text_field :username %>
    <br><br>
    
    <%= form.label :Password %>
    <%= form.text_field :password %>
    <br><br>

    <%= form.label :Confirm_Password %>
    <%= form.text_field :password_confirmation %>
    
    <br><br>
    <%= form.submit :Create_User %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Welcome Users</h1>


<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table border="2" >
  <thead>
    <tr>
      <th>Firstnme</th>
      <th>LastName</th>
      <th>Email</th>
      <th>Age</th>
      <th>Degree</th>
      <th>Year</th>
      <th>Company Name</th>
      <th>Website</th>
      <th>User Name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= user.age %></td>
        <td><%= user.degree %></td>
        <td><%= user.year %></td>
        <td><%= user.com_name %></td>
        <td><%= user.website %></td>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Address', address_index_path %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>